# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          irrationally excited
paginate:       5
baseurl:        "https://cstavitsky.github.io/"
url:            "https://cstavitsky.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chris Stavitsky
  url:          http://cstavitsky.github.io
  email:        corridorr@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/cstavitsky/tale

# Gems
plugins:
  - jekyll-paginate
